# `numpy`

 - one of the core packages for numerical computing in python
 - many packages are built on top of numpy
 - `numpy` has been optimized for procesing: faster due to memory access


In [1]:
# import Numpy with standard abbreviation
import numpy as np

# Variables
We can think about variables as a name we assign to a particular object in Python. For example,

In [2]:
# assign a small array to a variable a 
a = np.array( [ [1,1,2],[3,5,8] ]  )

When we run the cell, we store the variable and its value. We can see the variables value in two ways:

In [3]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
print(a)

[[1 1 2]
 [3 5 8]]


## Naming Variables
In the class we are going to use `snake_case` for naming variables.

# Variables and objects 

**object**: often encountered in Python documentation and turtorials.

object is a bundle of properties and actions about something specific 

Example:
- object: data frame
-properties: number of rows, names of columns, data created
-actions: selecting a row, adding a column

A variable is a name we give a specific object, and the same object can be referenced bu different variables.

Example:

- The Sun (actual star at the center of the solar system) = object
- sol = Spanish word for Sun = variable
- soleil = French word for sun = variable 

In practice: we will use object and variable interchangeably 


# Types

Each object in Python has a type.

type = what kind of object it is 

We can also call the type of the object, the **class** of the object.

We can see the type/class of an object by using the `type` function.

In [6]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

the `numpy.ndarray` is the core object/data type in the Numpy package. We can check the tye of an entry in an array by indexing.

In [8]:
# access first row and first column and what is the type of this output
print(a[0,0])
type(a[0,0])

1


numpy.int64

In [9]:
# how would you access the value 5 in the array a?
print(a[1,1])

5


# Functions 

`print` was our first example of a Python function! :)
A function:
- take in a set of **arguments**, separated by commas, and 
- use those orguments to product some **output**

argument = parameter : you might see argument more often in the documentation

We can ask information about a function by executing `?`followed by the function name

In [10]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its arguments in paranthesis
- then a short description of what the function does 
- finally, a list of the arguments and a brief explanation of each of them.

Different types of arguments inside the paranthesis. Roughly speaking there are two types of arguments:

- **non-optional arguments**: arguments you need to specify for the function to do something
- **optional argument**: arguments that are pre-filled by a default value by the function, but we can override them. Optional arguments appear inside the paranthesis () in the form 

`optional argument = default_value`

In [12]:
print('changing the default end argument of the print function', end=':)')

changing the default end argument of the print function:)

In [13]:
print('changing the default end argument of the print function')

changing the default end argument of the print function


# Attributes & Methods
An object in Python has attributes and methods.

- **attributes**: a property of an object, a piece of information about it.
- **methods**: a procedure associated with an object, an action where the main ingrediant is the object itself.

cats have attributes: weight, height, color and methods: chase(), eat(), nap()

Access a variable's attributes and methods by adding a period '.' at the end of the variable's name.

'variable.variable_method()' or 

'variable.variable_attribute'

Examples:

Methods and attributes of Numpy arrays:

In [1]:
import numpy as np

In [3]:
# define a 3x3 array
var = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# shape: attribute telling us 
# the number of elements in each dimension of the array
var.shape

(3, 3)

In [5]:
type(var.shape)

tuple

In [6]:
# ndim is an attribute holding the number of array dimensions
var.ndim

2

In [7]:
type(var.ndim)

int

- Notice attributes can have many different data types.

Examples of methods:

In [8]:
# min method for array
# return the minimum value in the array
var.min()

1

In [9]:
type(var.min)

builtin_function_or_method

# R & Python
R:
- does not use methods within an object
- functions in R are extrinsic to (outside) the objects they are acting on

Example : recreate getting the mean value in an array

In R there would be two separate items: the variable 'var' and a *separate* function 'min' that gets 'var' as a parameter:


```
#this is R code
var <- array(c(1,4,7,2,5,8,3,6,9)), dim = c(3,3)
min(var)
```

Using the pipe operator >%> in R's tidyverse is closer to the '.' in Python:
```
var <- array(c(1,4,7,2,5,8,3,6,9)), dim = c(3,3)
var <
